import Head from "next/head";
import { useState } from "react";

import Form from "@/components/Form";
import Result from "@/components/Result";

const Home = () => {
    const [result, setResult] = useState("");

    return (
        <>
            <Head>
                <title>Solution Preparation Calculator</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Form setResult={setResult} />
            <Result>{result}</Result>
        </>
    );
};

export default Home;
